// Bundled Pangasinan barangays for offline, reliable address selection.
export const PANGASINAN_BARANGAYS = {
  "Agno": [
    "ALLABON",
    "ALOLENG",
    "BANGAN-ODA",
    "BARUAN",
    "BOBOY",
    "CAYUNGNAN",
    "DANGLEY",
    "GAYUSAN",
    "MACABOBONI",
    "MAGSAYSAY",
    "NAMATUCAN",
    "PATAR",
    "POBLACION EAST",
    "POBLACION WEST",
    "SAN JUAN",
    "TUPA",
    "VIGA"
  ],
  "Aguilar": [
    "BAYAOAS",
    "BAYBAY",
    "BOCACLIW",
    "BOCBOC EAST",
    "BOCBOC WEST",
    "BUER",
    "CALSIB",
    "LAOAG",
    "MANLOCBOC",
    "NINOY",
    "PANACOL",
    "POBLACION",
    "POGOMBOA",
    "POGONSILI",
    "SAN JOSE",
    "TAMPAC"
  ],
  "Alaminos City": [
    "ALOS",
    "AMANDIEGO",
    "AMANGBANGAN",
    "BALANGOBONG",
    "BALAYANG",
    "BALEYADAAN",
    "BISOCOL",
    "BOLANEY",
    "BUED",
    "CABATUAN",
    "CAYUCAY",
    "DULACAC",
    "INERANGAN",
    "LANDOC",
    "LINMANSANGAN",
    "LUCAP",
    "MAAWI",
    "MACATIW",
    "MAGSAYSAY",
    "MONA",
    "PALAMIS",
    "PANDAN",
    "PANGAPISAN",
    "POBLACION",
    "POCALPOCAL",
    "POGO",
    "POLO",
    "QUIBUAR",
    "SABANGAN",
    "SAN ANTONIO (R. MAGSAYSAY)",
    "SAN JOSE",
    "SAN ROQUE",
    "SAN VICENTE",
    "SANTA MARIA",
    "TANAYTAY",
    "TANGCARANG",
    "TAWINTAWIN",
    "TELBANG",
    "VICTORIA"
  ],
  "Alcala": [
    "ANULID",
    "ATAINAN",
    "BERSAMIN",
    "CANARVACANAN",
    "CARANGLAAN",
    "CURARENG",
    "GUALSIC",
    "KASIKIS",
    "LAOAC",
    "MACAYO",
    "PINDANGAN CENTRO",
    "PINDANGAN EAST",
    "PINDANGAN WEST",
    "POBLACION EAST",
    "POBLACION WEST",
    "SAN JUAN",
    "SAN NICOLAS",
    "SAN PEDRO APARTADO",
    "SAN PEDRO ILI",
    "SAN VICENTE",
    "VACANTE"
  ],
  "Anda": [
    "AWAG",
    "AWILE",
    "BATIARAO",
    "CABUNGAN",
    "CAROT",
    "DOLAOAN",
    "IMBO",
    "MACALEENG",
    "MACANDOCANDONG",
    "MAL-ONG",
    "NAMAGBAGAN",
    "POBLACION",
    "ROXAS",
    "SABLIG",
    "SAN JOSE",
    "SIAPAR",
    "TONDOL",
    "TORITORI"
  ],
  "Asingan": [
    "ARISTON ESTE",
    "ARISTON WESTE",
    "BANTOG",
    "BARO",
    "BOBONAN",
    "CABALITIAN",
    "CALEPAAN",
    "CAROSUCAN NORTE",
    "CAROSUCAN SUR",
    "COLDIT",
    "DOMANPOT",
    "DUPAC",
    "MACALONG",
    "PALARIS",
    "POBLACION EAST",
    "POBLACION WEST",
    "SAN VICENTE ESTE",
    "SAN VICENTE WESTE",
    "SANCHEZ",
    "SOBOL",
    "TOBOY"
  ],
  "Balungao": [
    "ANGAYAN NORTE",
    "ANGAYAN SUR",
    "CAPULAAN",
    "ESMERALDA",
    "KITA-KITA",
    "MABINI",
    "MAUBAN",
    "POBLACION",
    "PUGARO",
    "RAJAL",
    "SAN ANDRES",
    "SAN AURELIO 1ST",
    "SAN AURELIO 2ND",
    "SAN AURELIO 3RD",
    "SAN JOAQUIN",
    "SAN JULIAN",
    "SAN LEON",
    "SAN MARCELINO",
    "SAN MIGUEL",
    "SAN RAYMUNDO"
  ],
  "Bani": [
    "AMBABAAY",
    "APORAO",
    "ARWAS",
    "BALLAG",
    "BANOG NORTE",
    "BANOG SUR",
    "CALABENG",
    "CENTRO TOMA",
    "COLAYO",
    "DACAP NORTE",
    "DACAP SUR",
    "GARRITA",
    "LUAC",
    "MACABIT",
    "MASIDEM",
    "POBLACION",
    "QUINAOAYANAN",
    "RANAO",
    "RANOM ILOCO",
    "SAN JOSE",
    "SAN MIGUEL",
    "SAN SIMON",
    "SAN VICENTE",
    "TIEP",
    "TIPOR",
    "TUGUI GRANDE",
    "TUGUI NORTE"
  ],
  "Basista": [
    "ANAMBONGAN",
    "BAYOYONG",
    "CABELDATAN",
    "DUMPAY",
    "MALIMPEC EAST",
    "MAPOLOPOLO",
    "NALNERAN",
    "NAVATAT",
    "OBONG",
    "OSMENA SR.",
    "PALMA",
    "PATACBO",
    "POBLACION"
  ],
  "Bautista": [
    "ARTACHO",
    "BALUYOT",
    "CABUAAN",
    "CACANDONGAN",
    "DIAZ",
    "KETEGAN",
    "NANDACAN",
    "NIBALIW NORTE",
    "NIBALIW SUR",
    "PALISOC",
    "POBLACION EAST",
    "POBLACION WEST",
    "POGO",
    "POPONTO",
    "PRIMICIAS",
    "SINABAAN",
    "VACANTE",
    "VILLANUEVA"
  ],
  "Bayambang": [
    "ALINGGAN",
    "AMAMPEREZ",
    "AMANCOSILING NORTE",
    "AMANCOSILING SUR",
    "AMBAYAT I",
    "AMBAYAT II",
    "APALEN",
    "ASIN",
    "ATAYNAN",
    "BACNONO",
    "BALAYBUAYA",
    "BANABAN",
    "BANI",
    "BATANGCAWA",
    "BELENG",
    "BICAL NORTE",
    "BICAL SUR",
    "BONGATO EAST",
    "BONGATO WEST",
    "BUAYAEN",
    "BUENLAG 1ST",
    "BUENLAG 2ND",
    "CADRE SITE",
    "CARUNGAY",
    "CATURAY",
    "DARAWEY (TANGAL)",
    "DUERA",
    "DUSOC",
    "HERMOZA",
    "IDONG",
    "INANLORENZANA",
    "INIRANGAN",
    "ITON",
    "LANGIRAN",
    "LIGUE",
    "M. H. DEL PILAR",
    "MACAYOCAYO",
    "MAGSAYSAY",
    "MAIGPA",
    "MALIMPEC",
    "MALIOER",
    "MANAGOS",
    "MANAMBONG NORTE",
    "MANAMBONG PARTE",
    "MANAMBONG SUR",
    "MANGAYAO",
    "NALSIAN NORTE",
    "NALSIAN SUR",
    "PANGDEL",
    "PANTOL",
    "PARAGOS",
    "POBLACION SUR",
    "PUGO",
    "REYNADO",
    "SAN GABRIEL 1ST",
    "SAN GABRIEL 2ND",
    "SAN VICENTE",
    "SANGCAGULIS",
    "SANLIBO",
    "SAPANG",
    "TAMARO",
    "TAMBAC",
    "TAMPOG",
    "TANOLONG",
    "TATARAO",
    "TELBANG",
    "TOCOC EAST",
    "TOCOC WEST",
    "WARDING",
    "WAWA",
    "ZONE I (POB.)",
    "ZONE II (POB.)",
    "ZONE III (POB.)",
    "ZONE IV (POB.)",
    "ZONE V (POB.)",
    "ZONE VI (POB.)",
    "ZONE VII (POB.)"
  ],
  "Binalonan": [
    "BALANGOBONG",
    "BUED",
    "BUGAYONG",
    "CAMANGAAN",
    "CANARVACANAN",
    "CAPAS",
    "CILI",
    "DUMAYAT",
    "LINMANSANGAN",
    "MANGCASUY",
    "MORENO",
    "PASILENG NORTE",
    "PASILENG SUR",
    "POBLACION",
    "SAN FELIPE CENTRAL",
    "SAN FELIPE SUR",
    "SAN PABLO",
    "SANTA CATALINA",
    "SANTA MARIA NORTE",
    "SANTIAGO",
    "SANTO NIÑO",
    "SUMABNIT",
    "TABUYOC",
    "VACANTE"
  ],
  "Binmaley": [
    "AMANCORO",
    "BALAGAN",
    "BALOGO",
    "BASING",
    "BAYBAY LOPEZ",
    "BAYBAY POLONG",
    "BIEC",
    "BUENLAG",
    "CALIT",
    "CALOOCAN DUPO",
    "CALOOCAN NORTE",
    "CALOOCAN SUR",
    "CAMALEY",
    "CANAOALAN",
    "DULAG",
    "GAYAMAN",
    "LINOC",
    "LOMBOY",
    "MALINDONG",
    "MANAT",
    "NAGPALANGAN",
    "NAGUILAYAN",
    "PALLAS",
    "PAPAGUEYAN",
    "PARAYAO",
    "POBLACION",
    "POTOTAN",
    "SABANGAN",
    "SALAPINGAO",
    "SAN ISIDRO NORTE",
    "SAN ISIDRO SUR",
    "SANTA ROSA",
    "TOMBOR"
  ],
  "Bolinao": [
    "ARNEDO",
    "BALINGASAY",
    "BINABALIAN",
    "CABUYAO",
    "CATUDAY",
    "CATUNGI",
    "CONCORDIA (POB.)",
    "CULANG",
    "DEWEY",
    "ESTANZA",
    "GERMINAL (POB.)",
    "GOYODEN",
    "ILOGMALINO",
    "LAMBES (LAMES)",
    "LIWA-LIWA",
    "LUCERO",
    "LUCIENTE 1.0",
    "LUCIENTE 2.0",
    "LUNA",
    "PATAR",
    "PILAR",
    "SALUD",
    "SAMANG NORTE",
    "SAMANG SUR",
    "SAMPALOC",
    "SAN ROQUE",
    "TARA",
    "TUPA",
    "VICTORY",
    "ZARAGOZA"
  ],
  "Bugallon": [
    "ANGARIAN",
    "ASINAN",
    "BACABAC",
    "BANAGA",
    "BOLAOEN",
    "BUENLAG",
    "CABAYAOASAN",
    "CAYANGA",
    "GUESET",
    "HACIENDA",
    "LAGUIT CENTRO",
    "LAGUIT PADILLA",
    "MAGTAKING",
    "PANGASCASAN",
    "PANTAL",
    "POBLACION",
    "POLONG",
    "PORTIC",
    "SALASA",
    "SALOMAGUE NORTE",
    "SALOMAGUE SUR",
    "SAMAT",
    "SAN FRANCISCO",
    "UMANDAY"
  ],
  "Burgos": [
    "ANAPAO (BUR ANAPAC)",
    "CACAYASEN",
    "CONCORDIA",
    "DON MATIAS",
    "ILIO-ILIO (ILIW-ILIW)",
    "PAPALLASEN",
    "POBLACION",
    "POGORUAC",
    "SAN MIGUEL",
    "SAN PASCUAL",
    "SAN VICENTE",
    "SAPA GRANDE",
    "SAPA PEQUEÑA",
    "TAMBACAN"
  ],
  "Calasiao": [
    "AMBONAO",
    "AMBUETEL",
    "BANAOANG",
    "BUED",
    "BUENLAG",
    "CABILOCAAN",
    "DINALAOAN",
    "DOYONG",
    "GABON",
    "LASIP",
    "LONGOS",
    "LUMBANG",
    "MACABITO",
    "MALABAGO",
    "MANCUP",
    "NAGSAING",
    "NALSIAN",
    "POBLACION EAST",
    "POBLACION WEST",
    "QUESBAN",
    "SAN MIGUEL",
    "SAN VICENTE",
    "SONGKOY",
    "TALIBAEW"
  ],
  "Dagupan City": [
    "BACAYAO NORTE",
    "BACAYAO SUR",
    "BARANGAY I (T. BUGALLON)",
    "BARANGAY II (NUEVA)",
    "BARANGAY IV (ZAMORA)",
    "BOLOSAN",
    "BONUAN BINLOC",
    "BONUAN BOQUIG",
    "BONUAN GUESET",
    "CALMAY",
    "CARAEL",
    "CARANGLAAN",
    "HERRERO",
    "LASIP CHICO",
    "LASIP GRANDE",
    "LOMBOY",
    "LUCAO",
    "MALUED",
    "MAMALINGLING",
    "MANGIN",
    "MAYOMBO",
    "PANTAL",
    "POBLACION OESTE",
    "POGO CHICO",
    "POGO GRANDE",
    "PUGARO SUIT",
    "SALAPINGAO",
    "SALISAY",
    "TAMBAC",
    "TAPUAC",
    "TEBENG"
  ],
  "Dasol": [
    "ALILAO",
    "AMALBALAN",
    "BOBONOT",
    "EGUIA",
    "GAIS-GUIPE",
    "HERMOSA",
    "MACALANG",
    "MAGSAYSAY",
    "MALACAPAS",
    "MALIMPIN",
    "OSMEÑA",
    "PETAL",
    "POBLACION",
    "SAN VICENTE",
    "TAMBAC",
    "TAMBOBONG",
    "ULI",
    "VIGA"
  ],
  "Infanta": [
    "BABUYAN",
    "BAMBAN",
    "BATANG",
    "BAYAMBANG",
    "CATO",
    "DOLIMAN",
    "FATIMA",
    "MAYA",
    "NANGALISAN",
    "NAYOM",
    "PITA",
    "POBLACION",
    "POTOL"
  ],
  "Labrador": [
    "BOLO",
    "BONGALON",
    "DULIG",
    "LAOIS",
    "MAGSAYSAY",
    "POBLACION",
    "SAN GONZALO",
    "SAN JOSE",
    "TOBUAN",
    "UYONG"
  ],
  "Lingayen": [
    "ALIWEKWEK",
    "BAAY",
    "BALANGOBONG",
    "BALOCOC",
    "BANTAYAN",
    "BASING",
    "CAPANDANAN",
    "DOMALANDAN CENTER",
    "DOMALANDAN EAST",
    "DOMALANDAN WEST",
    "DORONGAN",
    "DULAG",
    "ESTANZA",
    "LASIP",
    "LIBSONG EAST",
    "LIBSONG WEST",
    "MALAWA",
    "MALIMPUEC",
    "MANIBOC",
    "MATALAVA",
    "NAGUELGUEL",
    "NAMOLAN",
    "PANGAPISAN NORTH",
    "PANGAPISAN SUR",
    "POBLACION",
    "QUIBAOL",
    "ROSARIO",
    "SABANGAN",
    "TALOGTOG",
    "TONTON",
    "TUMBAR",
    "WAWA"
  ],
  "Mabini": [
    "BACNIT",
    "BARLO",
    "CAABIANGAAN",
    "CABANAETAN",
    "CABINUANGAN",
    "CALZADA",
    "CARANGLAAN",
    "DE GUZMAN",
    "LUNA",
    "MAGALONG",
    "NIBALIW",
    "PATAR",
    "POBLACION",
    "SAN PEDRO",
    "TAGUDIN",
    "VILLACORTA"
  ],
  "Malasiqui": [
    "ABONAGAN",
    "AGDAO",
    "ALACAN",
    "ALIAGA",
    "AMACALAN",
    "ANOLID",
    "APAYA",
    "ASIN ESTE",
    "ASIN WESTE",
    "BACUNDAO ESTE",
    "BACUNDAO WESTE",
    "BAKITIW",
    "BALITE",
    "BANAWANG",
    "BARANG",
    "BAWER",
    "BINALAY",
    "BOBON",
    "BOLAOIT",
    "BONGAR",
    "BUTAO",
    "CABATLING",
    "CABUELDATAN",
    "CALBUEG",
    "CANAN NORTE",
    "CANAN SUR",
    "CAWAYAN BOGTONG",
    "DON PEDRO",
    "GATANG",
    "GOLIMAN",
    "GOMEZ",
    "GUILIG",
    "ICAN",
    "INGALAGALA",
    "LAREG-LAREG",
    "LASIP",
    "LEPA",
    "LOQUEB ESTE",
    "LOQUEB NORTE",
    "LOQUEB SUR",
    "LUNEC",
    "MABULITEC",
    "MALIMPEC",
    "MANGGAN-DAMPAY",
    "NALSIAN NORTE",
    "NALSIAN SUR",
    "NANCAPIAN",
    "NANSANGAAN",
    "OLEA",
    "PACUAN",
    "PALAPAR NORTE",
    "PALAPAR SUR",
    "PALONG",
    "PAMARANUM",
    "PASIMA",
    "PAYAR",
    "POBLACION",
    "POLONG NORTE",
    "POLONG SUR",
    "POTIOCAN",
    "SAN JULIAN",
    "TABO-SILI",
    "TALOSPATANG",
    "TALOY",
    "TALOYAN",
    "TAMBAC",
    "TOBOR",
    "TOLONGUAT",
    "TOMLING",
    "UMANDO",
    "VIADO",
    "WAIG",
    "WAREY"
  ],
  "Manaoag": [
    "BABASIT",
    "BAGUINAY",
    "BARITAO",
    "BISAL",
    "BUCAO",
    "CABANBANAN",
    "CALAOCAN",
    "INAMOTAN",
    "LELEMAAN",
    "LICSI",
    "LIPIT NORTE",
    "LIPIT SUR",
    "MATOLONG",
    "MERMER",
    "NALSIAN",
    "ORAAN EAST",
    "ORAAN WEST",
    "PANTAL",
    "PAO",
    "PARIAN",
    "POBLACION",
    "PUGARO",
    "SAN RAMON",
    "SANTA INES",
    "SAPANG",
    "TEBUEL"
  ],
  "Mangaldan": [
    "ALITAYA",
    "AMANSABINA",
    "ANOLID",
    "BANAOANG",
    "BANTAYAN",
    "BARI",
    "BATENG",
    "BUENLAG",
    "DAVID",
    "EMBARCADERO",
    "GUEGUESANGEN",
    "GUESANG",
    "GUIGUILONEN",
    "GUILIG",
    "INLAMBO",
    "LANAS",
    "LANDAS",
    "MAASIN",
    "MACAYUG",
    "MALABAGO",
    "NAVALUAN",
    "NIBALIW",
    "OSIEM",
    "PALUA",
    "POBLACION",
    "POGO",
    "SALAAN",
    "SALAY",
    "TALOGTOG",
    "TEBAG"
  ],
  "Mangatarem": [
    "ANDANGIN",
    "ARELLANO STREET (POB.)",
    "BANTAY",
    "BANTOCALING",
    "BARACBAC",
    "BOGTONG BOLO",
    "BOGTONG BUNAO",
    "BOGTONG CENTRO",
    "BOGTONG NIOG",
    "BOGTONG SILAG",
    "BUAYA",
    "BUENLAG",
    "BUENO",
    "BUNAGAN",
    "BUNLALACAO",
    "BURGOS STREET (POB.)",
    "CABALUYAN 1ST",
    "CABALUYAN 2ND",
    "CABARABUAN",
    "CABARUAN",
    "CABAYAOASAN",
    "CABAYUGAN",
    "CACAOITEN",
    "CALUMBOYAN NORTE",
    "CALUMBOYAN SUR",
    "CALVO (POB.)",
    "CASILAGAN",
    "CATARATARAAN",
    "CATURAY NORTE",
    "CATURAY SUR",
    "CAVIERNESAN",
    "DORONGAN KETAKET",
    "DORONGAN LINMANSANGAN",
    "DORONGAN PUNTA",
    "DORONGAN SAWAT",
    "DORONGAN VALERIO",
    "GENERAL LUNA (POB.)",
    "HISTORIA",
    "LAWAK LANGKA",
    "LINMANSANGAN",
    "LOPEZ (POB.)",
    "MABINI (POB.)",
    "MACARANG",
    "MALABOBO",
    "MALIBONG",
    "MALUNEC",
    "MARAVILLA (POB.)",
    "MARAVILLA-ARELLANO EXT. (POB.)",
    "MUELANG",
    "NAGUILAYAN EAST",
    "NAGUILAYAN WEST",
    "NANCASALAN",
    "NIOG-CABISON-BULANEY",
    "OLEGARIO-CAOILE (POB.)",
    "OLO CACAMPOSAN",
    "OLO CAFABROSAN",
    "OLO CAGARLITAN",
    "OSMEÑA (POB.)",
    "PACALAT",
    "PAMPANO",
    "PARIAN",
    "PAUL",
    "PEANIA PEDANIA (BEDANIA)",
    "POGON-ANIAT",
    "POGON-LOMBOY (POB.)",
    "PONGLO-BALEG",
    "PONGLO-MUELAG",
    "QUETEGAN (POGON-BALEG)",
    "QUEZON (POB.)",
    "SALAVANTE",
    "SAPANG",
    "SONSON ONGKIT",
    "SUACO",
    "TAGAC",
    "TAKIPAN",
    "TALOGTOG",
    "TOCOC BARIKIR",
    "TORRE 1ST",
    "TORRE 2ND",
    "TORRES BUGALLON (POB.)",
    "UMANGAN",
    "ZAMORA (POB.)"
  ],
  "Mapandan": [
    "AMANOAOAC",
    "APAYA",
    "ASERDA",
    "BALOLING",
    "CORAL",
    "GOLDEN",
    "JIMENEZ",
    "LAMBAYAN",
    "LUYAN (LUYAN SOUTH)",
    "NILOMBOT",
    "PIAS",
    "POBLACION",
    "PRIMICIAS",
    "SANTA MARIA (LUYAN NORTH)",
    "TORRES"
  ],
  "Natividad": [
    "BARANGOBONG",
    "BATCHELOR EAST",
    "BATCHELOR WEST",
    "BURGOS (SAN NARCISO)",
    "CACANDUNGAN",
    "CALAPUGAN",
    "CANAREM",
    "LUNA",
    "POBLACION EAST",
    "POBLACION WEST",
    "RIZAL",
    "SALUD",
    "SAN EUGENIO",
    "SAN MACARIO NORTE",
    "SAN MACARIO SUR",
    "SAN MAXIMO",
    "SAN MIGUEL",
    "SILAG"
  ],
  "Pozorrubio": [
    "ALIPANGPANG",
    "AMAGBAGAN",
    "BALACAG",
    "BANDING",
    "BANTUGAN",
    "BATAKIL",
    "BOBONAN",
    "BUNEG",
    "CABLONG",
    "CASANFERNANDOAN",
    "CASTAÑO",
    "DILAN",
    "DON BENITO",
    "HAWAY",
    "IMBALBALATONG",
    "INOMAN",
    "LAOAC",
    "MAAMBAL",
    "MALASIN",
    "MALOKIAT",
    "MANAOL",
    "NAMA",
    "NANTANGALAN",
    "PALACPALAC",
    "PALGUYOD",
    "POBLACION I",
    "POBLACION II",
    "POBLACION III",
    "POBLACION IV",
    "ROSARIO",
    "SUGCONG",
    "TALOGTOG",
    "TULNAC",
    "VILLEGAS"
  ],
  "Rosales": [
    "ACOP",
    "BAKITBAKIT",
    "BALINGCANAWAY",
    "CABALAOANGAN NORTE",
    "CABALAOANGAN SUR",
    "CALANUTAN (DON FELIX COLOMA)",
    "CAMANGAAN",
    "CAPITAN TOMAS",
    "CARMAY EAST",
    "CARMAY WEST",
    "CARMEN EAST",
    "CARMEN WEST",
    "CASANICOLASAN",
    "COLILING",
    "DON ANTONIO VILLAGE",
    "GUILING",
    "PALAKIPAK",
    "PANGAOAN",
    "RABAGO",
    "RIZAL",
    "SALVACION",
    "SAN ANGEL",
    "SAN ANTONIO",
    "SAN BARTOLOME",
    "SAN ISIDRO",
    "SAN LUIS",
    "SAN PEDRO EAST",
    "SAN PEDRO WEST",
    "SAN VICENTE",
    "STATION DISTRICT",
    "TOMANA EAST",
    "TOMANA WEST",
    "ZONE I (POB.)",
    "ZONE II (POB.)",
    "ZONE III (POB.)",
    "ZONE IV (POB.)",
    "ZONE V (POB.)"
  ],
  "San Carlos City": [
    "ABANON",
    "AGDAO",
    "ANANDO",
    "ANO",
    "ANTIPANGOL",
    "APONIT",
    "BACNAR",
    "BALAYA",
    "BALAYONG",
    "BALDOG",
    "BALITE SUR",
    "BALOCOC",
    "BANI",
    "BEGA",
    "BOCBOC",
    "BOGAOAN",
    "BOLINGIT",
    "BOLOSAN",
    "BONIFACIO (POB.)",
    "BUENGLAT",
    "BUGALLON-POSADAS STREET (POB.)",
    "BURGOS PADLAN (POB.)",
    "CACARITAN",
    "CAINGAL",
    "CALOBAOAN",
    "CALOMBOYAN",
    "CAOAYAN-KILING",
    "CAPATAAN",
    "COBOL",
    "COLILING",
    "CRUZ",
    "DOYONG",
    "GAMATA",
    "GUELEW",
    "ILANG",
    "INERANGAN",
    "ISLA",
    "LIBAS",
    "LILIMASAN",
    "LONGOS",
    "LUCBAN (POB.)",
    "M. SORIANO",
    "MABALBALINO",
    "MABINI (POB.)",
    "MAGTAKING",
    "MALACAÑANG",
    "MALIWARA",
    "MAMARLAO",
    "MANZON",
    "MATAGDEM",
    "MESTIZO NORTE",
    "NAGUILAYAN",
    "NILENTAP",
    "PADILLA-GOMEZ",
    "PAGAL",
    "PAITAN-PANOYPOY",
    "PALAMING",
    "PALARIS (POB.)",
    "PALOSPOS",
    "PANGALANGAN",
    "PANGOLOAN",
    "PANGPANG",
    "PARAYAO",
    "PAYAPA",
    "PAYAR",
    "PEREZ BOULEVARD (POB.)",
    "PNR STATION SITE",
    "POLO",
    "QUEZON BOULEVARD (POB.)",
    "QUINTONG",
    "RIZAL (POB.)",
    "ROXAS BOULEVARD (POB.)",
    "SALINAP",
    "SAN JUAN",
    "SAN PEDRO-TALOY",
    "SAPINIT",
    "SUPO",
    "TALANG",
    "TAMAYO",
    "TANDANG SORA",
    "TANDOC",
    "TARECE",
    "TARECTEC",
    "TAYAMBANI",
    "TEBAG",
    "TURAC"
  ],
  "San Fabian": [
    "ALACAN",
    "AMBALANGAN-DALIN",
    "ANGIO",
    "ANONANG",
    "ARAMAL",
    "BIGBIGA",
    "BINDAY",
    "BOLAOEN",
    "BOLASI",
    "CABARUAN",
    "CAYANGA",
    "COLISAO",
    "GOMOT",
    "INMALOG",
    "INMALOG NORTE",
    "LEKEP-BUTAO",
    "LIPIT-TOMEENG",
    "LONGOS",
    "LONGOS PROPER",
    "LONGOS-AMANGONAN-PARAC-PARAC FABRICA",
    "MABILAO",
    "NIBALIW CENTRAL",
    "NIBALIW EAST",
    "NIBALIW MAGLIBA",
    "NIBALIW NARVARTE (NIBALIW WEST COMPOUND)",
    "NIBALIW VIDAL (NIBALIW WEST PROPER)",
    "PALAPAD",
    "POBLACION",
    "RABON",
    "SAGUD-BAHLEY",
    "SOBOL",
    "TEMPRA-GUILIG",
    "TIBLONG",
    "TOCOK"
  ],
  "San Jacinto": [
    "AWAI",
    "BAGONG PAG-ASA (POBLACION EAST)",
    "BOLO",
    "CAPAOAY (POB.)",
    "CASIBONG",
    "GUIBEL",
    "IMELDA (DECRITO)",
    "LABNEY",
    "LOBONG",
    "MACAYUG",
    "MAGSAYSAY (CAPAY)",
    "SAN GUILLERMO (POBLACION WEST)",
    "SAN JOSE",
    "SAN JUAN",
    "SAN ROQUE",
    "SAN VICENTE",
    "SANTA CRUZ",
    "SANTA MARIA",
    "SANTO TOMAS"
  ],
  "San Manuel": [
    "CABACARAAN",
    "CABARITAN",
    "FLORES",
    "GUISET NORTE (POB.)",
    "GUISET SUR (POB.)",
    "LAPALO",
    "NAGSAAG",
    "NARRA",
    "SAN ANTONIO-ARZADON",
    "SAN BONIFACIO",
    "SAN JUAN",
    "SAN ROQUE",
    "SAN VICENTE",
    "SANTO DOMINGO"
  ],
  "San Nicolas": [
    "BENSICAN",
    "CABITNONGAN",
    "CABOLOAN",
    "CACABUGAOAN",
    "CALANUTIAN",
    "CALAOCAN",
    "CAMANGGAAN",
    "CAMINDOROAN",
    "CASARATAN",
    "DALUMPINAS",
    "FIANZA",
    "LUNGAO",
    "MALICO",
    "MALILION",
    "NAGKAYSA",
    "NINING",
    "POBLACION EAST",
    "POBLACION WEST",
    "SALINGCOB",
    "SALPAD",
    "SAN FELIPE EAST",
    "SAN FELIPE WEST",
    "SAN ISIDRO (STA. CRUZAN)",
    "SAN JOSE",
    "SAN RAFAEL CENTRO",
    "SAN RAFAEL EAST",
    "SAN RAFAEL WEST",
    "SAN ROQUE",
    "SANTA MARIA EAST",
    "SANTA MARIA WEST",
    "SANTO TOMAS",
    "SIBLOT",
    "SOBOL"
  ],
  "San Quintin": [
    "ALAC",
    "BALIGAYAN",
    "BANTOG",
    "BOLINTAGUEN",
    "CABALAOANGAN",
    "CABANGARAN",
    "CALOMBOYAN",
    "CARAYACAN",
    "CASANTAMARIAN",
    "GONZALO",
    "LABUAN",
    "LAGASIT",
    "LUMAYAO",
    "MABINI",
    "MANTACDANG",
    "NANGAPUGAN",
    "POBLACION ZONE I",
    "POBLACION ZONE II",
    "POBLACION ZONE III",
    "SAN PEDRO",
    "UNGIB"
  ],
  "Santa Barbara": [
    "ALIBAGO",
    "BALINGUEO",
    "BANAOANG",
    "BANZAL",
    "BOTAO",
    "CABLONG",
    "CARUSOCAN",
    "DALONGUE",
    "ERFE",
    "GUEGUESANGEN",
    "LEET",
    "MALANAY",
    "MANINGDING",
    "MARONONG",
    "MATICMATIC",
    "MINIEN EAST",
    "MINIEN WEST",
    "NILOMBOT",
    "PATAYAC",
    "PAYAS",
    "POBLACION NORTE",
    "POBLACION SUR",
    "PRIMICIAS (VENTINILLA WEST)",
    "SAPANG",
    "SONQUIL",
    "TEBAG EAST",
    "TEBAG WEST",
    "TULIAO",
    "VENTINILLA (VENTINILLA EAST)"
  ],
  "Santa Maria": [
    "BAL-LOY",
    "BANTOG",
    "CABOLUAN",
    "CAL-LITANG",
    "CAPANDANAN",
    "CAUPLASAN",
    "DALAYAP",
    "LIBSONG",
    "NAMAGBAGAN",
    "PAITAN",
    "PATAQUID",
    "PILAR",
    "POBLACION EAST",
    "POBLACION WEST",
    "PUGOT",
    "SAMON",
    "SAN ALEJANDRO",
    "SAN MARIANO",
    "SAN PABLO",
    "SAN PATRICIO",
    "SAN VICENTE",
    "SANTA CRUZ",
    "SANTA ROSA"
  ],
  "Santo Tomas": [
    "LA LUNA",
    "POBLACION EAST",
    "POBLACION WEST",
    "SALVACION",
    "SAN AGUSTIN",
    "SAN ANTONIO",
    "SAN JOSE",
    "SAN MARCOS",
    "SANTO DOMINGO",
    "SANTO NIÑO"
  ],
  "Sison": [
    "AGAT",
    "ALIBENG",
    "AMAGBAGAN",
    "ARTACHO",
    "ASAN NORTE",
    "ASAN SUR",
    "BANTAY INSIK",
    "BILA",
    "BINMECKEG",
    "BULAOEN EAST",
    "BULAOEN WEST",
    "CABARITAN",
    "CALUNETAN",
    "CAMANGAAN",
    "CAURINGAN",
    "DUNGON",
    "ESPERANZA",
    "INMALOG",
    "KILLO",
    "LABAYUG",
    "PALDIT",
    "PINDANGAN",
    "PINMILAPIL",
    "POBLACION CENTRAL",
    "POBLACION NORTE",
    "POBLACION SUR",
    "SAGUNTO",
    "TARA-TARA"
  ],
  "Sual": [
    "BAQUIOEN",
    "BAYBAY NORTE",
    "BAYBAY SUR",
    "BOLAOEN",
    "CABALITIAN",
    "CALUMBUYAN",
    "CAMAGSINGALAN",
    "CAOAYAN",
    "CAPANTOLAN",
    "MACAYCAYAWAN",
    "PAITAN EAST",
    "PAITAN WEST",
    "PANGASCASAN",
    "POBLACION",
    "SANTO DOMINGO",
    "SESELANGEN",
    "SIOASIO EAST",
    "SIOASIO WEST",
    "VICTORIA"
  ],
  "Tayug": [
    "AGNO",
    "AMISTAD",
    "BARANGAY A (POB.)",
    "BARANGAY B (POB.)",
    "BARANGAY C (POB.)",
    "BARANGAY D (POB.)",
    "BARANGOBONG",
    "C. LICHAUCO",
    "CARRIEDO",
    "EVANGELISTA",
    "GUZON",
    "LAWAK",
    "LEGASPI",
    "LIBERTAD",
    "MAGALLANES",
    "PANGANIBAN",
    "SALENG",
    "SANTO DOMINGO",
    "TOKETEC",
    "TRENCHERA",
    "ZAMORA"
  ],
  "Umingan": [
    "ABOT MOLINA",
    "ALO-O",
    "AMARONAN",
    "ANNAM",
    "BANTUG",
    "BARACBAC",
    "BARAT",
    "BUENAVISTA",
    "CABALITIAN",
    "CABANGARAN",
    "CABARUAN",
    "CABATUAN",
    "CADIZ",
    "CALITLITAN",
    "CAPAS",
    "CARAYUNGAN SUR",
    "CAROSALESAN",
    "CASILAN",
    "CAURDANETAAN",
    "CONCEPCION",
    "DECRETO",
    "DEL ROSARIO",
    "DIAZ",
    "DIKET",
    "DON JUSTO ABALOS (CAROAN)",
    "DON MONTANO",
    "ESPERANZA",
    "EVANGELISTA",
    "FLORES",
    "FULGOSINO",
    "GONZALES",
    "LA PAZ",
    "LABUAN",
    "LAUREN",
    "LUBONG",
    "LUNA ESTE",
    "LUNA WESTE",
    "MANTACDANG",
    "MASEIL-SEIL",
    "NAMPALCAN",
    "NANCALABASAAN",
    "PANGANGAAN",
    "PAPALLASEN",
    "PEMIENTA",
    "POBLACION EAST",
    "POBLACION WEST",
    "PRADO",
    "RESURRECCION",
    "RICOS",
    "SAN ANDRES",
    "SAN JUAN",
    "SAN LEON",
    "SAN PABLO",
    "SAN VICENTE",
    "SANTA MARIA",
    "SANTA ROSA",
    "SINABAAN",
    "TANGGAL SAWANG"
  ],
  "Urbiztondo": [
    "ANGATEL",
    "BALANGAY",
    "BATANGCAOA",
    "BAUG",
    "BAYAOAS",
    "BITUAG",
    "CAMAMBUGAN",
    "DALANGIRING",
    "DUPLAC",
    "GALARIN",
    "GUETEB",
    "MALACA",
    "MALAYO",
    "MALIBONG",
    "PASIBI EAST",
    "PASIBI WEST",
    "PISUAC",
    "POBLACION",
    "REAL",
    "SALAVANTE",
    "SAWAT"
  ],
  "Urdaneta City": [
    "ANONAS",
    "BACTAD EAST",
    "BAYAOAS",
    "BOLAOEN",
    "CABARUAN",
    "CABULOAN",
    "CAMANANG",
    "CAMANTILES",
    "CASANTAAN",
    "CATABLAN",
    "CAYAMBANAN",
    "CONSOLACION",
    "DILAN PAURIDO",
    "DR. PEDRO T. ORATA (BACTAD PROPER)",
    "LABIT PROPER",
    "LABIT WEST",
    "MABANOGBOG",
    "MACALONG",
    "NANCALOBASAAN",
    "NANCAMALIRAN EAST",
    "NANCAMALIRAN WEST",
    "NANCAYASAN",
    "OLTAMA",
    "PALINA EAST",
    "PALINA WEST",
    "PINMALUDPOD",
    "POBLACION",
    "SAN JOSE",
    "SAN VICENTE",
    "SANTA LUCIA",
    "SANTO DOMINGO",
    "SUGCONG",
    "TIPUSO",
    "TULONG"
  ],
  "Villasis": [
    "AMAMPEREZ",
    "BACAG",
    "BARANGOBONG",
    "BARRACA",
    "CAPULAAN",
    "CARAMUTAN",
    "LA PAZ",
    "LABIT",
    "LIPAY",
    "LOMBOY",
    "PIAZ (PLAZA)",
    "PUELAY",
    "SAN BLAS",
    "SAN NICOLAS",
    "TOMBOD",
    "UNZAD",
    "ZONE I (POB.)",
    "ZONE II (POB.)",
    "ZONE III (POB.)",
    "ZONE IV (POB.)",
    "ZONE V (POB.)"
  ],
  "Laoac": [
    "ANIS",
    "BALLIGI",
    "BANUAR",
    "BOTIQUE",
    "CAARINGAYAN",
    "CABILAOAN WEST",
    "CABULALAAN",
    "CALAOAGAN",
    "CALMAY",
    "CASAMPAGAAN",
    "CASANESTEBANAN",
    "CASANTIAGOAN",
    "DOMINGO ALARCIO (CABILAOAN EAST)",
    "INMANDUYAN",
    "LEBUEG",
    "MARABOC",
    "NANBAGATAN",
    "PANAGA",
    "POBLACION (LAOAC)",
    "TALOGTOG",
    "TURKO",
    "YATYAT"
  ]
};
